### ISSUE TITLE
Incorrect id for room K1.105

### ISSUE THREAD

**Issue by cbeyls** [FOSDEM/maps#141]
Room ids should follow the fosdem website convention so that deep linking can work in the apps.

Room k1.105 currently has id k1105_lafontaine instead of k1105_la_fontaine so deep linking does not work for that room.

Reference: https://fosdem.org/2017/schedule/room/k1105_la_fontaine/

**Comment by ShinIce** [comment]
fixed on 65910f6

**Comment by cbeyls** [comment]
Too bad you didn't push it to production for this Sunday... Live site is still broken
